/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description Return a portfolio's identity + base currency (404 if it doesn't exist).
         */
        get: operations["get_portfolio_api_v1_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions
         * @description Return the portfolio's full ledger as typed transactions.
         */
        get: operations["list_transactions_api_v1_portfolios__portfolio_id__transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Holdings
         * @description Return the portfolio's tracked securities + classification metadata.
         */
        get: operations["list_holdings_api_v1_portfolios__portfolio_id__holdings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytics
         * @description Return aggregated cost-basis / realized-P&L / XIRR analytics (404 if absent).
         */
        get: operations["get_analytics_api_v1_portfolios__portfolio_id__analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — cheap check that the app is up (no DB touch).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AllocationWeight
         * @description One row of an allocation breakdown.
         */
        AllocationWeight: {
            /** Key */
            key: string;
            /** Market Value */
            market_value: string;
            /** Weight */
            weight: string;
        };
        /**
         * CostBasisResult
         * @description Outcome of replaying a ticker's ledger under FIFO lot accounting.
         */
        CostBasisResult: {
            /** Ticker */
            ticker: string;
            /** Open Quantity */
            open_quantity: string;
            /** Open Cost Basis Base */
            open_cost_basis_base: string;
            /** Realized Pnl Base */
            realized_pnl_base: string;
            /** Dividends Base */
            dividends_base: string;
            /** Fees Base */
            fees_base: string;
            /** Open Lots */
            open_lots: components["schemas"]["OpenLot"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HoldingInfo
         * @description A tracked security's classification metadata (provider output).
         *
         *     Grouping keys for allocation roll-ups; the market value is joined in later once
         *     the market-data layer (§1.3) can price the position.
         */
        HoldingInfo: {
            /** Ticker */
            ticker: string;
            /** Sector */
            sector?: string | null;
            /** Industry */
            industry?: string | null;
        };
        /**
         * OpenLot
         * @description An unclosed FIFO purchase lot, valued in the portfolio base currency.
         */
        OpenLot: {
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Quantity */
            quantity: string;
            /** Cost Per Share Base */
            cost_per_share_base: string;
        };
        /**
         * PortfolioAnalytics
         * @description Aggregated, base-currency portfolio analytics (the service layer's output).
         *
         *     This is the single typed envelope the ``/analytics`` endpoint returns. It bundles
         *     the portfolio identity, per-position FIFO cost-basis results, whole-portfolio
         *     roll-up totals, and the money-weighted return (XIRR).
         *
         *     ``money_weighted_return`` is ``None`` when XIRR is mathematically undefined
         *     (e.g. an empty ledger, or flows that never change sign) — we surface "not
         *     computable" honestly rather than emitting a misleading ``0``. It is a *rate*
         *     (annualized fraction), not money, but is kept as ``Decimal`` so no ``float``
         *     leaks into a financial payload.
         *
         *     Market-value-dependent figures — per-position unrealized P&L and allocation
         *     weights — are populated when the market-data provider supplies current
         *     prices. When prices are unavailable (no provider configured, quota exhausted,
         *     or a missing FX rate) those fields degrade gracefully: totals are ``None``,
         *     allocation lists are empty, and the affected tickers are reported in
         *     ``unpriced_tickers`` so the omission is explicit, never a silent ``0``.
         */
        PortfolioAnalytics: {
            portfolio: components["schemas"]["PortfolioSummary"];
            /** Base Currency */
            base_currency: string;
            /** Positions */
            positions: components["schemas"]["CostBasisResult"][];
            /** Realized Pnl Base */
            realized_pnl_base: string;
            /** Dividends Base */
            dividends_base: string;
            /** Fees Base */
            fees_base: string;
            /** Open Cost Basis Base */
            open_cost_basis_base: string;
            /** Money Weighted Return */
            money_weighted_return?: string | null;
            /**
             * Positions Unrealized
             * @default []
             */
            positions_unrealized: components["schemas"]["UnrealizedResult"][];
            /** Market Value Base */
            market_value_base?: string | null;
            /** Unrealized Pnl Base */
            unrealized_pnl_base?: string | null;
            /**
             * Allocation By Ticker
             * @default []
             */
            allocation_by_ticker: components["schemas"]["AllocationWeight"][];
            /**
             * Allocation By Sector
             * @default []
             */
            allocation_by_sector: components["schemas"]["AllocationWeight"][];
            /**
             * Allocation By Industry
             * @default []
             */
            allocation_by_industry: components["schemas"]["AllocationWeight"][];
            /**
             * Unpriced Tickers
             * @default []
             */
            unpriced_tickers: string[];
            /** Priced As Of */
            priced_as_of?: string | null;
        };
        /**
         * PortfolioSummary
         * @description Lightweight portfolio identity + reporting base currency (provider output).
         */
        PortfolioSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Base Currency */
            base_currency: string;
        };
        /**
         * Transaction
         * @description A single dated ledger event for one ticker, in its native currency.
         *
         *     Field usage by ``type``:
         *
         *     * ``BUY`` / ``SELL``: ``quantity`` (> 0) and ``price`` per share; ``fees`` optional.
         *     * ``DIVIDEND``: ``amount`` = total cash received (native currency).
         *     * ``FEE``: ``amount`` = total fee paid (native currency).
         *     * ``SPLIT``: ``split_ratio`` (e.g. ``2`` for a 2-for-1); other fields ignored.
         */
        Transaction: {
            /** Ticker */
            ticker: string;
            type: components["schemas"]["TransactionType"];
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Currency */
            currency: string;
            /**
             * Quantity
             * @default 0
             */
            quantity: string;
            /**
             * Price
             * @default 0
             */
            price: string;
            /**
             * Fees
             * @default 0
             */
            fees: string;
            /**
             * Amount
             * @default 0
             */
            amount: string;
            /**
             * Split Ratio
             * @default 1
             */
            split_ratio: string;
            /** Sector */
            sector?: string | null;
            /** Industry */
            industry?: string | null;
        };
        /**
         * TransactionType
         * @description Ledger event kinds supported by the deterministic calculators.
         * @enum {string}
         */
        TransactionType: "BUY" | "SELL" | "DIVIDEND" | "FEE" | "SPLIT";
        /**
         * UnrealizedResult
         * @description Mark-to-market of open lots against a current price.
         */
        UnrealizedResult: {
            /** Ticker */
            ticker: string;
            /** Open Quantity */
            open_quantity: string;
            /** Open Cost Basis Base */
            open_cost_basis_base: string;
            /** Market Value Base */
            market_value_base: string;
            /** Unrealized Pnl Base */
            unrealized_pnl_base: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_portfolio_api_v1_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_v1_portfolios__portfolio_id__transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_holdings_api_v1_portfolios__portfolio_id__holdings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_api_v1_portfolios__portfolio_id__analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioAnalytics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
