/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Portfolios
         * @description Return every tracked portfolio, for the UI's portfolio picker.
         *
         *     Declared before ``/{portfolio_id}`` so FastAPI matches this literal path first.
         */
        get: operations["list_portfolios_api_v1_portfolios_get"];
        put?: never;
        /**
         * Create Portfolio
         * @description Create a new empty portfolio and return its assigned identity.
         */
        post: operations["create_portfolio_api_v1_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description Return a portfolio's identity + base currency (404 if it doesn't exist).
         */
        get: operations["get_portfolio_api_v1_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions
         * @description Return the portfolio's full ledger as typed transactions.
         */
        get: operations["list_transactions_api_v1_portfolios__portfolio_id__transactions_get"];
        put?: never;
        /**
         * Add Transactions
         * @description Append manually-entered ledger events (404 if the portfolio is absent).
         */
        post: operations["add_transactions_api_v1_portfolios__portfolio_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Holdings
         * @description Return the portfolio's tracked securities + classification metadata.
         */
        get: operations["list_holdings_api_v1_portfolios__portfolio_id__holdings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytics
         * @description Return aggregated cost-basis / realized-P&L / XIRR analytics (404 if absent).
         */
        get: operations["get_analytics_api_v1_portfolios__portfolio_id__analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Positions
         * @description Record current-holding snapshots as opening BUY lots (404 if absent).
         *
         *     This is the fast on-ramp for an existing portfolio: assert each position's
         *     ticker, quantity, and cost basis instead of re-keying years of trades.
         */
        post: operations["add_positions_api_v1_portfolios__portfolio_id__positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Imports
         * @description Return the portfolio's import history, newest first.
         */
        get: operations["list_imports_api_v1_portfolios__portfolio_id__imports_get"];
        put?: never;
        /**
         * Create Import
         * @description Accept a broker statement and process it in the background.
         *
         *     Returns ``202 Accepted`` immediately with a ``PENDING`` job — a decade-long
         *     export can hold thousands of rows, far too slow to finish inside the request.
         *     Poll ``GET /portfolios/{id}/imports/{job_id}`` until the status is terminal,
         *     then refetch analytics.
         *
         *     The upload's declared ``content_type`` is untrusted browser metadata, so the
         *     format comes from ``source_format`` and the parser validates the actual bytes.
         *     Re-uploading identical content is rejected with ``409`` (it would double-count
         *     the whole ledger); pass ``allow_duplicate=true`` to override deliberately.
         */
        post: operations["create_import_api_v1_portfolios__portfolio_id__imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/imports/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Import
         * @description Return one import job's live status/progress (the endpoint the UI polls).
         */
        get: operations["get_import_api_v1_portfolios__portfolio_id__imports__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — cheap check that the app is up (no DB touch).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AllocationWeight
         * @description One row of an allocation breakdown.
         */
        AllocationWeight: {
            /** Key */
            key: string;
            /** Market Value */
            market_value: string;
            /** Weight */
            weight: string;
        };
        /** Body_create_import_api_v1_portfolios__portfolio_id__imports_post */
        Body_create_import_api_v1_portfolios__portfolio_id__imports_post: {
            /** File */
            file: string;
        };
        /**
         * CostBasisResult
         * @description Outcome of replaying a ticker's ledger under FIFO lot accounting.
         */
        CostBasisResult: {
            /** Ticker */
            ticker: string;
            /** Open Quantity */
            open_quantity: string;
            /** Open Cost Basis Base */
            open_cost_basis_base: string;
            /** Realized Pnl Base */
            realized_pnl_base: string;
            /** Dividends Base */
            dividends_base: string;
            /** Fees Base */
            fees_base: string;
            /** Open Lots */
            open_lots: components["schemas"]["OpenLot"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HoldingInfo
         * @description A tracked security's classification metadata (provider output).
         *
         *     Grouping keys for allocation roll-ups; the market value is joined in later once
         *     the market-data layer (§1.3) can price the position.
         */
        HoldingInfo: {
            /** Ticker */
            ticker: string;
            /** Sector */
            sector?: string | null;
            /** Industry */
            industry?: string | null;
        };
        /**
         * ImportStatus
         * @description Lifecycle of an asynchronous statement import.
         * @enum {string}
         */
        ImportStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
        /**
         * LedgerIngestResult
         * @description What a write/import operation actually recorded (the endpoint's response).
         */
        LedgerIngestResult: {
            /** Portfolio Id */
            portfolio_id: number;
            /** Created Transactions */
            created_transactions: number;
            /** Tickers */
            tickers: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            source_format?: components["schemas"]["StatementFormat"] | null;
        };
        /**
         * OpenLot
         * @description An unclosed FIFO purchase lot, valued in the portfolio base currency.
         */
        OpenLot: {
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Quantity */
            quantity: string;
            /** Cost Per Share Base */
            cost_per_share_base: string;
        };
        /**
         * PortfolioAnalytics
         * @description Aggregated, base-currency portfolio analytics (the service layer's output).
         *
         *     This is the single typed envelope the ``/analytics`` endpoint returns. It bundles
         *     the portfolio identity, per-position FIFO cost-basis results, whole-portfolio
         *     roll-up totals, and the money-weighted return (XIRR).
         *
         *     ``money_weighted_return`` is ``None`` when XIRR is mathematically undefined
         *     (e.g. an empty ledger, or flows that never change sign) — we surface "not
         *     computable" honestly rather than emitting a misleading ``0``. It is a *rate*
         *     (annualized fraction), not money, but is kept as ``Decimal`` so no ``float``
         *     leaks into a financial payload.
         *
         *     Market-value-dependent figures — per-position unrealized P&L and allocation
         *     weights — are populated when the market-data provider supplies current
         *     prices. When prices are unavailable (no provider configured, quota exhausted,
         *     or a missing FX rate) those fields degrade gracefully: totals are ``None``,
         *     allocation lists are empty, and the affected tickers are reported in
         *     ``unpriced_tickers`` so the omission is explicit, never a silent ``0``.
         */
        PortfolioAnalytics: {
            portfolio: components["schemas"]["PortfolioSummary"];
            /** Base Currency */
            base_currency: string;
            /** Positions */
            positions: components["schemas"]["CostBasisResult"][];
            /** Realized Pnl Base */
            realized_pnl_base: string;
            /** Dividends Base */
            dividends_base: string;
            /** Fees Base */
            fees_base: string;
            /** Open Cost Basis Base */
            open_cost_basis_base: string;
            /** Money Weighted Return */
            money_weighted_return?: string | null;
            /**
             * Positions Unrealized
             * @default []
             */
            positions_unrealized: components["schemas"]["UnrealizedResult"][];
            /** Market Value Base */
            market_value_base?: string | null;
            /** Unrealized Pnl Base */
            unrealized_pnl_base?: string | null;
            /**
             * Allocation By Ticker
             * @default []
             */
            allocation_by_ticker: components["schemas"]["AllocationWeight"][];
            /**
             * Allocation By Sector
             * @default []
             */
            allocation_by_sector: components["schemas"]["AllocationWeight"][];
            /**
             * Allocation By Industry
             * @default []
             */
            allocation_by_industry: components["schemas"]["AllocationWeight"][];
            /**
             * Unpriced Tickers
             * @default []
             */
            unpriced_tickers: string[];
            /** Priced As Of */
            priced_as_of?: string | null;
        };
        /**
         * PortfolioCreate
         * @description Request body to create a new (empty) portfolio.
         */
        PortfolioCreate: {
            /** Name */
            name: string;
            /** Base Currency */
            base_currency: string;
        };
        /**
         * PortfolioSummary
         * @description Lightweight portfolio identity + reporting base currency (provider output).
         */
        PortfolioSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Base Currency */
            base_currency: string;
        };
        /**
         * PositionSnapshot
         * @description A user's *current* holding, captured without full transaction history.
         *
         *     This is the answer to "my portfolio is 10 years old and I don't want to key in
         *     every trade": you assert the position as it stands today — how many shares you
         *     hold and what they cost — and the system records it as a single opening ``BUY``
         *     lot in the ledger. Every downstream calculator then treats it like any other
         *     lot, so cost-basis and unrealized P&L are exact.
         *
         *     Provide the cost basis exactly one of two ways (brokerages report both):
         *
         *     * ``cost_basis_per_share`` — the average price paid per share, or
         *     * ``total_cost_basis`` — the aggregate amount invested (we divide by quantity).
         *
         *     ``as_of`` is the acquisition/opening date. When you genuinely don't know it,
         *     leave it unset and the service stamps today's date — but note the money-weighted
         *     return (XIRR) is only meaningful with a *real* purchase date, so a snapshot with
         *     a placeholder date will (correctly) leave XIRR undefined while cost-basis and
         *     unrealized P&L stay exact.
         */
        PositionSnapshot: {
            /** Ticker */
            ticker: string;
            /** Quantity */
            quantity: number | string;
            /** Currency */
            currency: string;
            /** As Of */
            as_of?: string | null;
            /** Cost Basis Per Share */
            cost_basis_per_share?: number | string | null;
            /** Total Cost Basis */
            total_cost_basis?: number | string | null;
            /** Sector */
            sector?: string | null;
            /** Industry */
            industry?: string | null;
        };
        /**
         * StatementFormat
         * @description Supported broker statement layouts for the import endpoint.
         * @enum {string}
         */
        StatementFormat: "robinhood_csv";
        /**
         * StatementImportStatus
         * @description Progress + outcome of one statement import (what the UI polls).
         *
         *     A decade-long export can hold thousands of rows, so the upload endpoint returns
         *     immediately with this record in ``PENDING`` and the work continues in the
         *     background. The client polls until ``status`` is terminal.
         *
         *     ``processed_rows``/``total_rows`` drive a progress bar. ``total_rows`` is
         *     ``None`` until parsing has counted the file, because an honest "unknown" is
         *     better than a fake denominator that makes a progress bar jump backwards.
         */
        StatementImportStatus: {
            /** Id */
            id: number;
            /** Portfolio Id */
            portfolio_id: number;
            status: components["schemas"]["ImportStatus"];
            source_format: components["schemas"]["StatementFormat"];
            /** Original Filename */
            original_filename: string;
            /** Checksum */
            checksum: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Total Rows */
            total_rows?: number | null;
            /**
             * Processed Rows
             * @default 0
             */
            processed_rows: number;
            /**
             * Created Transactions
             * @default 0
             */
            created_transactions: number;
            /**
             * Tickers
             * @default []
             */
            tickers: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            /** Error */
            error?: string | null;
        };
        /**
         * Transaction
         * @description A single dated ledger event for one ticker, in its native currency.
         *
         *     Field usage by ``type``:
         *
         *     * ``BUY`` / ``SELL``: ``quantity`` (> 0) and ``price`` per share; ``fees`` optional.
         *     * ``DIVIDEND``: ``amount`` = total cash received (native currency).
         *     * ``FEE``: ``amount`` = total fee paid (native currency).
         *     * ``SPLIT``: ``split_ratio`` (e.g. ``2`` for a 2-for-1); other fields ignored.
         */
        "Transaction-Input": {
            /** Ticker */
            ticker: string;
            type: components["schemas"]["TransactionType"];
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Currency */
            currency: string;
            /**
             * Quantity
             * @default 0
             */
            quantity: number | string;
            /**
             * Price
             * @default 0
             */
            price: number | string;
            /**
             * Fees
             * @default 0
             */
            fees: number | string;
            /**
             * Amount
             * @default 0
             */
            amount: number | string;
            /**
             * Split Ratio
             * @default 1
             */
            split_ratio: number | string;
            /** Sector */
            sector?: string | null;
            /** Industry */
            industry?: string | null;
        };
        /**
         * Transaction
         * @description A single dated ledger event for one ticker, in its native currency.
         *
         *     Field usage by ``type``:
         *
         *     * ``BUY`` / ``SELL``: ``quantity`` (> 0) and ``price`` per share; ``fees`` optional.
         *     * ``DIVIDEND``: ``amount`` = total cash received (native currency).
         *     * ``FEE``: ``amount`` = total fee paid (native currency).
         *     * ``SPLIT``: ``split_ratio`` (e.g. ``2`` for a 2-for-1); other fields ignored.
         */
        "Transaction-Output": {
            /** Ticker */
            ticker: string;
            type: components["schemas"]["TransactionType"];
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Currency */
            currency: string;
            /**
             * Quantity
             * @default 0
             */
            quantity: string;
            /**
             * Price
             * @default 0
             */
            price: string;
            /**
             * Fees
             * @default 0
             */
            fees: string;
            /**
             * Amount
             * @default 0
             */
            amount: string;
            /**
             * Split Ratio
             * @default 1
             */
            split_ratio: string;
            /** Sector */
            sector?: string | null;
            /** Industry */
            industry?: string | null;
        };
        /**
         * TransactionType
         * @description Ledger event kinds supported by the deterministic calculators.
         * @enum {string}
         */
        TransactionType: "BUY" | "SELL" | "DIVIDEND" | "FEE" | "SPLIT";
        /**
         * UnrealizedResult
         * @description Mark-to-market of open lots against a current price.
         */
        UnrealizedResult: {
            /** Ticker */
            ticker: string;
            /** Open Quantity */
            open_quantity: string;
            /** Open Cost Basis Base */
            open_cost_basis_base: string;
            /** Market Value Base */
            market_value_base: string;
            /** Unrealized Pnl Base */
            unrealized_pnl_base: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_portfolios_api_v1_portfolios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"][];
                };
            };
        };
    };
    create_portfolio_api_v1_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_v1_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_v1_portfolios__portfolio_id__transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction-Output"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_transactions_api_v1_portfolios__portfolio_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction-Input"][];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerIngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_holdings_api_v1_portfolios__portfolio_id__holdings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_api_v1_portfolios__portfolio_id__analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioAnalytics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_positions_api_v1_portfolios__portfolio_id__positions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionSnapshot"][];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerIngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_imports_api_v1_portfolios__portfolio_id__imports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementImportStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_import_api_v1_portfolios__portfolio_id__imports_post: {
        parameters: {
            query?: {
                source_format?: components["schemas"]["StatementFormat"];
                allow_duplicate?: boolean;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_import_api_v1_portfolios__portfolio_id__imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementImportStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_api_v1_portfolios__portfolio_id__imports__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementImportStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
